# Generated by Django 3.2.13 on 2022-11-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres_list',
            field=models.TextField(null=True),
        ),
    ]
