# Generated by Django 3.2.13 on 2022-11-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors_namelist',
            field=models.CharField(default='', max_length=100),
        ),
    ]
