# Generated by Django 3.2.13 on 2022-11-17 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
