# Generated by Django 3.2.13 on 2022-11-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors_namelist',
            field=models.CharField(default='', max_length=100),
        ),
    ]
